### ISSUE TITLE
'pip install git+https://github.com/fastai/fastai_dev' doen't work

### ISSUE THREAD

**Issue by YahngSungho** [fastai/fastai_dev#305]
The error message appears
```
 ERROR: Command errored out with exit status 1:
     command: /home/mskang/.conda/envs/sungho/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-113a4j57/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-113a4j57/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-113a4j57/pip-egg-info
         cwd: /tmp/pip-req-build-113a4j57/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-113a4j57/setup.py", line 5, in <module>
        exec(open('dev/local/version.py').read())
    FileNotFoundError: [Errno 2] No such file or directory: 'dev/local/version.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

Perhaps this is because the folder structure has changed recently. Previously it was `dev> local> version.py` but now it's` dev> fastai> version.py`

**Comment by sgugger** [comment]
Yes that has been solved since then.
